name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  sign:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile Source
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run lint
      - run: npm run build

      - name: web-ext build
        id: web-ext-build
        uses: kewisch/action-web-ext@v1.2
        with:
          cmd: build
          source: dist

      - name: web-ext sign
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1.2
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: listed
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          timeout: 900000

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
